export const GET_EQUIPMENT = 'GET_EQUIPMENT';
export const GET_BOOKMARK = 'GET_BOOKMARK';
export const GET_WORKOUT = 'GET_WORKOUT';
export const SCHEDULED_WORKOUT = 'SCHEDULED_WORKOUT'
export const FINISHED_WORKOUT  = 'FINISHED_WORKOUT'
export const WORKOUT_DETAIL = 'WORKOUT_DETAIL'
export const GET_WORKOUT_EXERCISES = 'GET_WORKOUT_EXERCISES'